services:
  asyncffmpeg:
    build:
      context: .
    image: futureys/asyncffmpeg:development
    volumes:
      - .:/workspace:cached
      - /workspace/.venv
      # - Using uv in Docker | uv
      #   https://docs.astral.sh/uv/guides/integration/docker/#caching
      - uv-cache:/root/.cache/uv
volumes:
  uv-cache:
